from typing import Callable, Optional

class MemorySystem:
    def __init__(
        self,
        config_file: str,
        working_dir: str,
        read_callback: Optional[Callable[[int], None]] = None,
        write_callback: Optional[Callable[[int], None]] = None,
    ) -> None: ...

    def print_stats(self) -> None: ...
    def reset_stats(self) -> None: ...
    def set_callbacks(
        self,
        read_complete: Optional[Callable[[int], None]] = None,
        write_complete: Optional[Callable[[int], None]] = None,
    ) -> None: ...
    def can_accept(self, addr: int, is_write: bool) -> bool: ...
    def enqueue(self, addr: int, is_write: bool) -> None: ...
    def tick(self) -> None: ...

    @property
    def clock_period(self) -> float: ...
    @property
    def queue_size(self) -> int: ...
    @property
    def burst_size(self) -> int: ...
