import numpy as np
import numpy.typing as npt

class SimEngine:
    def __init__(
        self,
        config_file: str,
        working_dir: str,
        collect_events: bool = True,
    ) -> None: ...
    def try_enqueue(self, addr: int, is_write: bool, tag: int = 0) -> bool: ...
    def tick(self, cycles: int = 1) -> int: ...
    def drain(self, max_cycles: int = 10000000) -> int: ...
    def tick_until_capacity(self, addr: int, is_write: bool, max_cycles: int = 10000000) -> int: ...
    def tick_until_completion(self, max_cycles: int = 10000000) -> int: ...
    def advance_to(self, target_cycle: int, stop_on_completion: bool = True) -> int: ...
    def advance_until(
        self,
        target_cycle: int,
        stop_on_tag_done: bool = True,
        max_cycles: int = 10000000,
    ) -> int: ...
    def advance_by(self, cycles: int, stop_on_tag_done: bool = True) -> int: ...
    def set_tag_quota(self, tag: int, remaining: int) -> None: ...
    def enqueue(self, addr: int, is_write: bool, tag: int = 0) -> bool: ...
    def enqueue_range(
        self,
        addr: int,
        count: int,
        stride: int,
        is_write: bool,
        tag: int = 0,
    ) -> int: ...
    def set_outstanding_cap(self, cap: int) -> None: ...
    def outstanding_cap(self) -> int: ...
    def advance_until_in_flight_below(self, cap: int, max_cycles: int = 10000000) -> int: ...
    def frontend_size(self) -> int: ...
    def channel_of(self, addr: int) -> int: ...
    def will_accept(self, addr: int, is_write: bool) -> bool: ...
    def unmatched_callbacks(self) -> int: ...
    def frontend_blocked_writes(self) -> int: ...
    def run_trace(
        self,
        addrs: npt.NDArray[np.uint64],
        writes: npt.NDArray[np.bool_],
        gap_cycles: int = 0,
        max_drain_cycles: int = 10000000,
    ) -> int: ...
    def set_collect(self, collect: bool) -> None: ...
    def take_read_completions(
        self,
    ) -> tuple[list[int], list[int], list[int], list[int]]: ...
    def take_write_completions(
        self,
    ) -> tuple[list[int], list[int], list[int], list[int]]: ...
    def take_read_completions_np(
        self,
    ) -> tuple[
        npt.NDArray[np.uint64],
        npt.NDArray[np.uint64],
        npt.NDArray[np.uint64],
        npt.NDArray[np.uint64],
    ]: ...
    def take_write_completions_np(
        self,
    ) -> tuple[
        npt.NDArray[np.uint64],
        npt.NDArray[np.uint64],
        npt.NDArray[np.uint64],
        npt.NDArray[np.uint64],
    ]: ...
    def take_completions(
        self,
    ) -> tuple[list[int], list[int], list[int], list[int], list[int]]: ...
    def num_outstanding(self) -> int: ...
    def in_flight(self) -> int: ...
    def num_outstanding_reads(self) -> int: ...
    def num_outstanding_writes(self) -> int: ...
    def print_stats(self) -> None: ...
    def reset_stats(self) -> None: ...
    @property
    def current_cycle(self) -> int: ...
    @property
    def clock_period(self) -> float: ...
    @property
    def queue_size(self) -> int: ...
    @property
    def burst_size(self) -> int: ...
    @property
    def num_channels(self) -> int: ...
    @property
    def memory_size(self) -> int: ...
